# Pandas

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

## 함수수

### 데이터 조회


In [ ]:
df=sns.load_dataset('titanic')

In [ ]:
df. head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [ ]:
df.tail()

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
890         0       3    male  32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

### null 확인

In [ ]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df.isnull().sum().sum()

869

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


### 통계
> count(), sum(), mean(), median(), min(), max(), abs(), std(),value_counts(),unique(), nunique(),describe()

In [ ]:
df_number=df.select_dtypes(include=np.number)
df_object=df.select_dtypes(exclude=np.number)

type(df)

pandas.core.frame.DataFrame

In [ ]:
df.shape

(891, 15)

In [ ]:
df_number.shape

(891, 6)

In [ ]:
print(f'df.shape: {df.shape} / df_number.shape : {df_number.shape}')

df.shape: (891, 15) / df_number.shape : (891, 6)


In [ ]:
print(f'df.shape: {df.shape} / df_number["age"].shape : {df_number["age"].shape}')

df.shape: (891, 15) / df_number["age"].shape : (891,)


In [ ]:
df_number.columns

Index(['survived', 'pclass', 'age', 'sibsp', 'parch', 'fare'], dtype='object')

In [ ]:
df_number['age'].median()

28.0

In [ ]:
df_number.mean(), df_number['age'].mean()

(survived     0.383838
 pclass       2.308642
 age         29.699118
 sibsp        0.523008
 parch        0.381594
 fare        32.204208
 dtype: float64, 29.69911764705882)

In [ ]:
df_number.max() - (df_number.std() + df_number.min()) # 가장 큰수 - (표준편차 + 가장 작은 수)

survived      0.513408
pclass        1.163929
age          65.053503
sibsp         6.897257
parch         5.193943
fare        462.635771
dtype: float64

In [ ]:
df_number.var()

survived       0.236772
pclass         0.699015
age          211.019125
sibsp          1.216043
parch          0.649728
fare        2469.436846
dtype: float64

In [ ]:
df_object['class'].value_counts()

Third     491
First     216
Second    184
Name: class, dtype: int64

In [ ]:
df_object['embarked'].value_counts()

S    644
C    168
Q     77
Name: embarked, dtype: int64

In [ ]:
print(df_object['embarked'].unique())
print(df_object['embarked'].nunique())

['S' 'C' 'Q' nan]
3


In [ ]:
df.describe(include='all') # 카테고리 전체

survived      pclass   sex         age       sibsp       parch  \
count   891.000000  891.000000   891  714.000000  891.000000  891.000000   
unique         NaN         NaN     2         NaN         NaN         NaN   
top            NaN         NaN  male         NaN         NaN         NaN   
freq           NaN         NaN   577         NaN         NaN         NaN   
mean      0.383838    2.308642   NaN   29.699118    0.523008    0.381594   
std       0.486592    0.836071   NaN   14.526497    1.102743    0.806057   
min       0.000000    1.000000   NaN    0.420000    0.000000    0.000000   
25%       0.000000    2.000000   NaN   20.125000    0.000000    0.000000   
50%       0.000000    3.000000   NaN   28.000000    0.000000    0.000000   
75%       1.000000    3.000000   NaN   38.000000    1.000000    0.000000   
max       1.000000    3.000000   NaN   80.000000    8.000000    6.000000   

              fare embarked  class  who adult_male deck  embark_town alive  \
count   891.000000      889    891  891        891  203          889   891   
unique         NaN        3      3    3          2    7            3     2   
top            NaN        S  Third  man       True    C  Southampton    no   
freq           NaN      644    491  537        537   59          644   549   
mean     32.204208      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
std      49.693429      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
min       0.000000      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
25%       7.910400      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
50%      14.454200      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
75%      31.000000      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
max     512.329200      NaN    NaN  NaN        NaN  NaN          NaN   NaN   

       alone  
count    891  
unique     2  
top     True  
freq     537  
mean     NaN  
std      NaN  
min      NaN  
25%      NaN  
50%      NaN  
75%      NaN  
max      NaN

In [ ]:
df.describe(include=np.number) # 수에 대한 카테고리 

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
df.describe(exclude=np.number)

sex embarked  class  who adult_male deck  embark_town alive alone
count    891      889    891  891        891  203          889   891   891
unique     2        3      3    3          2    7            3     2     2
top     male        S  Third  man       True    C  Southampton    no  True
freq     577      644    491  537        537   59          644   549   537

In [ ]:
df['adult_male'].describe() # Series도 사용

count      891
unique       2
top       True
freq       537
Name: adult_male, dtype: object

### map() : , apply()

#### map() : 치환, 변경 시 주로 사용

In [ ]:
x=pd.Series({'one':1, 'tow':2, 'three':3})
y=pd.Series({1: 'triangle',2: 'square',3:'circle'})

In [ ]:
x

one      1
tow      2
three    3
dtype: int64

In [ ]:
y

1    triangle
2      square
3      circle
dtype: object

In [ ]:
z=pd.Series({'triangle':'일', 'square':'이','circle':'삼'})

In [ ]:
x.map(y)

one      triangle
tow        square
three      circle
dtype: object

In [ ]:
x.map(y).map(z)

one      일
tow      이
three    삼
dtype: object

In [ ]:
df['sex'].unique()

array(['male', 'female'], dtype=object)

In [ ]:
df['sex'][:5]

0      male
1    female
2    female
3    female
4      male
Name: sex, dtype: object

In [ ]:
replace_dict = {"male":1, "female":0}
df['sex'].map(replace_dict)[:5]

0    1
1    0
2    0
3    0
4    1
Name: sex, dtype: int64

In [ ]:
df['sex'].map(lambda x: 1 if x == 'male' else 0)[:5]

0    1
1    0
2    0
3    0
4    1
Name: sex, dtype: int64

#### apply()

In [ ]:
df_tmp=pd.DataFrame(np.arange(12).reshape(4,3),columns=['a','b','c'])
df_tmp

a   b   c
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [ ]:
df_tmp['a'].apply(lambda x:x *2)

0     0
1     6
2    12
3    18
Name: a, dtype: int64

In [ ]:
df_tmp.apply(lambda x:x.sum()) # Series 합 = columns 합

a    18
b    22
c    26
dtype: int64

In [ ]:
df_tmp['row_sum'] = df_tmp.apply(lambda x:x.sum(), axis=1)
df_tmp 

a   b   c  row_sum
0  0   1   2        3
1  3   4   5       12
2  6   7   8       21
3  9  10  11       30

In [ ]:
df_tmp['a+2'] = df_tmp.apply(lambda x:x['a']+2, axis=1)
df_tmp 

a   b   c  row_sum  a+2
0  0   1   2        3    2
1  3   4   5       12    5
2  6   7   8       21    8
3  9  10  11       30   11

In [ ]:
def tmpFnc(a,b):
  return a+b

df_tmp['a+b'] = df_tmp.apply(lambda x:tmpFnc(x['a'], x['b']), axis=1)
df_tmp 

a   b   c  row_sum  a+2  a+b
0  0   1   2        3    2    1
1  3   4   5       12    5    7
2  6   7   8       21    8   13
3  9  10  11       30   11   19

### 집합


In [ ]:
select_cols = ['age', 'sex', 'pclass', 'fare', 'survived']
df_groupby = df[select_cols]
df_groupby.head()

age     sex  pclass     fare  survived
0  22.0    male       3   7.2500         0
1  38.0  female       1  71.2833         1
2  26.0  female       3   7.9250         1
3  35.0  female       1  53.1000         1
4  35.0    male       3   8.0500         0

#### pivot_table
> 데이터 중에서 두 개의 열을 각각 행 인덱스, 열 인덱스로 사용하여 데이터를 조회하는 것  

- 파라미터
  - data: 데이터프레임
  - values: 데이터로 사용할 열
  - index: 행으로 사용할 열
  - columns: 열로 사용할 열
  - aggfunc: 데이터 집계함수
  

In [ ]:
df_groupby.columns

Index(['age', 'sex', 'pclass', 'fare', 'survived'], dtype='object')

In [ ]:
pd.pivot_table(df_groupby, index='sex', columns='pclass', values='age', aggfunc='mean')

pclass          1          2          3
sex                                    
female  34.611765  28.722973  21.750000
male    41.281386  30.740707  26.507589

In [ ]:
pd.pivot_table(df_groupby, index='sex', columns='pclass', values='age', aggfunc=['min', 'max'])


min               max            
pclass     1     2     3     1     2     3
sex                                       
female  2.00  2.00  0.75  63.0  57.0  63.0
male    0.92  0.67  0.42  80.0  70.0  74.0

#### groupby


In [ ]:
grouped = df_groupby.groupby(['sex'])

In [ ]:
for i in grouped:
  print(type(i))

<class 'tuple'>
<class 'tuple'>


In [ ]:
for key, group in grouped:
  print("* key", key)
  print("* count", len(group))
  print(group.head())
  print('\n')

* key female
* count 314
    age     sex  pclass     fare  survived
1  38.0  female       1  71.2833         1
2  26.0  female       3   7.9250         1
3  35.0  female       1  53.1000         1
8  27.0  female       3  11.1333         1
9  14.0  female       2  30.0708         1


* key male
* count 577
    age   sex  pclass     fare  survived
0  22.0  male       3   7.2500         0
4  35.0  male       3   8.0500         0
5   NaN  male       3   8.4583         0
6  54.0  male       1  51.8625         0
7   2.0  male       3  21.0750         0




In [ ]:
grouped.mean()

age    pclass       fare  survived
sex                                             
female  27.915709  2.159236  44.479818  0.742038
male    30.726645  2.389948  25.523893  0.188908

In [ ]:
group_female = grouped.get_group('female')
group_female.head()

age     sex  pclass     fare  survived
1  38.0  female       1  71.2833         1
2  26.0  female       3   7.9250         1
3  35.0  female       1  53.1000         1
8  27.0  female       3  11.1333         1
9  14.0  female       2  30.0708         1

여러 컬럼을 기준으로 집합

In [ ]:
grouped = df_groupby.groupby(['sex','pclass'])

In [ ]:
for key, group in grouped:
  print("* key", key)
  print("* count", len(group))
  print(group.head())
  print('\n')

* key ('female', 1)
* count 94
     age     sex  pclass      fare  survived
1   38.0  female       1   71.2833         1
3   35.0  female       1   53.1000         1
11  58.0  female       1   26.5500         1
31   NaN  female       1  146.5208         1
52  49.0  female       1   76.7292         1


* key ('female', 2)
* count 76
     age     sex  pclass     fare  survived
9   14.0  female       2  30.0708         1
15  55.0  female       2  16.0000         1
41  27.0  female       2  21.0000         0
43   3.0  female       2  41.5792         1
53  29.0  female       2  26.0000         1


* key ('female', 3)
* count 144
     age     sex  pclass     fare  survived
2   26.0  female       3   7.9250         1
8   27.0  female       3  11.1333         1
10   4.0  female       3  16.7000         1
14  14.0  female       3   7.8542         0
18  31.0  female       3  18.0000         0


* key ('male', 1)
* count 122
     age   sex  pclass      fare  survived
6   54.0  male       1   51.8

In [ ]:
grouped.mean()

age        fare  survived
sex    pclass                                 
female 1       34.611765  106.125798  0.968085
       2       28.722973   21.970121  0.921053
       3       21.750000   16.118810  0.500000
male   1       41.281386   67.226127  0.368852
       2       30.740707   19.741782  0.157407
       3       26.507589   12.661633  0.135447

agg()


In [ ]:
df_groupby['fare'].agg(['sum', 'mean'])

sum     28693.949300
mean       32.204208
Name: fare, dtype: float64

In [ ]:
df_groupby['fare'].agg(lambda x:x.sum())

28693.9493

groupby()와 같이 사용

In [ ]:
grouped=df_groupby.groupby(['sex'])

In [ ]:
grouped.agg(['min','max'])

age       pclass      fare           survived    
         min   max    min max   min       max      min max
sex                                                       
female  0.75  63.0      1   3  6.75  512.3292        0   1
male    0.42  80.0      1   3  0.00  512.3292        0   1

In [ ]:
grouped.agg({
    'fare': ['min', 'max'],
    'age': 'mean'
})

fare                  age
         min       max       mean
sex                              
female  6.75  512.3292  27.915709
male    0.00  512.3292  30.726645

In [ ]:
def min_max(x):
  return x.max() - x.min()

grouped.agg(min_max)

age  pclass      fare  survived
sex                                      
female  62.25       2  505.5792         1
male    79.58       2  512.3292         1

transform()

In [ ]:
grouped=df_groupby.groupby(['pclass'])

In [ ]:
age_mean=grouped.age.mean()
age_std=grouped.age.std()

for key, group in grouped.age:
    group_zscore = (group - age_mean.loc[key]) / age_std.loc[key]
    print("* origin :", key)
    print(group_zscore.head(3))
    print('\n')

* origin : 1
1   -0.015770
3   -0.218434
6    1.065103
Name: age, dtype: float64


* origin : 2
9    -1.134029
15    1.794317
17         NaN
Name: age, dtype: float64


* origin : 3
0   -0.251342
2    0.068776
4    0.789041
Name: age, dtype: float64




In [ ]:
def z_score(x):
  return (x-x.mean())/x.std()

df_transform=grouped.age.transform(z_score)
print(df_transform.iloc[[1,3,6]])
print(df_transform.iloc[[9,15,17]])
print(df_transform.iloc[[0,2,4]])

1   -0.015770
3   -0.218434
6    1.065103
Name: age, dtype: float64
9    -1.134029
15    1.794317
17         NaN
Name: age, dtype: float64
0   -0.251342
2    0.068776
4    0.789041
Name: age, dtype: float64


기타 응용


In [ ]:
test = grouped.filter(lambda x: x.age.mean() < 30)

print(test.head())
print(test['pclass'].unique())

    age     sex  pclass     fare  survived
0  22.0    male       3   7.2500         0
2  26.0  female       3   7.9250         1
4  35.0    male       3   8.0500         0
5   NaN    male       3   8.4583         0
7   2.0    male       3  21.0750         0
[3 2]


In [ ]:
print(test['pclass'].describe())

count    675.000000
mean       2.727407
std        0.445623
min        2.000000
25%        2.000000
50%        3.000000
75%        3.000000
max        3.000000
Name: pclass, dtype: float64


In [ ]:
grouped.apply(lambda x : x.describe()) # 그룹별 통계정보

age  pclass        fare    survived
pclass                                                  
1      count  186.000000   216.0  216.000000  216.000000
       mean    38.233441     1.0   84.154687    0.629630
       std     14.802856     0.0   78.380373    0.484026
       min      0.920000     1.0    0.000000    0.000000
       25%     27.000000     1.0   30.923950    0.000000
       50%     37.000000     1.0   60.287500    1.000000
       75%     49.000000     1.0   93.500000    1.000000
       max     80.000000     1.0  512.329200    1.000000
2      count  173.000000   184.0  184.000000  184.000000
       mean    29.877630     2.0   20.662183    0.472826
       std     14.001077     0.0   13.417399    0.500623
       min      0.670000     2.0    0.000000    0.000000
       25%     23.000000     2.0   13.000000    0.000000
       50%     29.000000     2.0   14.250000    0.000000
       75%     36.000000     2.0   26.000000    1.000000
       max     70.000000     2.0   73.500000    1.000000
3      count  355.000000   491.0  491.000000  491.000000
       mean    25.140620     3.0   13.675550    0.242363
       std     12.495398     0.0   11.778142    0.428949
       min      0.420000     3.0    0.000000    0.000000
       25%     18.000000     3.0    7.750000    0.000000
       50%     24.000000     3.0    8.050000    0.000000
       75%     32.000000     3.0   15.500000    0.000000
       max     74.000000     3.0   69.550000    1.000000

### 예제


1. 각 컬럼별 결측치의 전체 비율율

In [ ]:
df.isnull().sum()/df.shape[0]
# (df.isnull().sum()/df.shape[0].round(4)).sort_values(ascending=False)

survived       0.000000
pclass         0.000000
sex            0.000000
age            0.198653
sibsp          0.000000
parch          0.000000
fare           0.000000
embarked       0.002245
class          0.000000
who            0.000000
adult_male     0.000000
deck           0.772166
embark_town    0.002245
alive          0.000000
alone          0.000000
dtype: float64

In [ ]:
np.random.seed(42)
arr=np.random.randint(50,101,(4,3))
arr

array([[88, 78, 64],
       [92, 57, 70],
       [88, 68, 72],
       [60, 60, 73]])

In [ ]:
df=pd.DataFrame(arr)

2. 컬럼/로우 기준으로 평균값 구하기기

In [ ]:
print('컬럼 기준 평균')

print(df.iloc[:].mean())
print(arr.mean(axis=0))

컬럼 기준 평균
0    82.00
1    65.75
2    69.75
dtype: float64
[82.   65.75 69.75]


In [ ]:
print('로우 기준 평균')

print('0 :' , df.loc[0,:].mean())
print('1 :' , df.loc[1,:].mean())
print('2 :' , df.loc[2,:].mean())
print('3 :' , df.loc[3,:].mean())
print(arr.mean(axis=1))

로우 기준 평균
0 : 76.66666666666667
1 : 73.0
2 : 76.0
3 : 64.33333333333333
[76.66666667 73.         76.         64.33333333]


3. (2, 2) 형태로 92, 57, 88, 68 조회회

In [ ]:
df.loc[1:2,0:1]

0   1
1  92  57
2  88  68

In [ ]:
arr[1:3, :2]

array([[92, 57],
       [88, 68]])