# Numpy 행렬 및 배열 연산

1. ###  Numpy array vs Python list

 >##### Numpy array : Python list 보다 빠르고 작다. 코드 최적화




2. ### 배열 생성

In [14]:
import numpy as np
lst=[
    [1,2,3],
    [4,5,6]
]

arr=np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
scalar = 1
vector=np.array([1,2,3,4])
vector_f =np.array([1,2,3,4,5,6],float)

In [25]:
print(type(vector), type(vector_f))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [26]:
vector.shape, vector_f.shape

((4,), (6,))

In [27]:
vector.dtype, vector_f.dtype

(dtype('int64'), dtype('float64'))

In [30]:
vec1=np.array([1,2,3,4,5,6])
vec2=np.array([[1,2,3],[4,5,6]])

In [31]:
vec1.size, vec2.size

(6, 6)

In [32]:
vec1.shape, vec2.shape

((6,), (2, 3))

In [33]:
vec1.shape[0], vec2.shape[0]

(6, 2)

In [38]:
vec2[0,0], vec2[1,2]

(1, 6)

- ##### 특수 배열 생성성

In [44]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

In [45]:
arr1 = np.array(range(0,10))

In [54]:
arr2 = np.arange(0,10)

In [70]:
arr.ndim, arr1.ndim, arr2.ndim

(1, 1, 1)

In [98]:
arr4=np.array([[1,2,3,],[4,4,5],[6,6,6,],[7,7,7]])
arr5=np.array([[1,2,3,],[4,4,5],[6,6,6,],[7,7,7],[8,8,8]])
arr6=np.array([[[1,2,3],[4,5,6]],[[3,4,5],[7,8,9]],[[1,2,3],[4,5,6]],[[3,4,5],[7,8,9]]])
arr4.ndim, arr5.ndim, arr6.ndim
print(arr6, arr6.shape, arr6.ndim)
# ndim 행렬의 차원수 : []개수 / 3차원 : (2d 갯수, 1d 갯수, scala 갯수) / n차원 : ((n-1)차원갯수, , , , , ,scalar갯수)

[[[1 2 3]
  [4 5 6]]

 [[3 4 5]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]]

 [[3 4 5]
  [7 8 9]]] (4, 2, 3) 3


In [72]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [64]:
np.full((2,5),6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [65]:
rg=np.random.default_rng(1)

In [69]:
np.floor(100*rg.random((2,2))), np.floor(3*rg.random((2,2)))

(array([[54.,  2.],
        [75., 53.]]), array([[0., 2.],
        [0., 1.]]))

- ##### 배열의 결합



In [76]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[0,0,0]])

In [81]:
print(np.vstack((arr1,arr2)))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 0 0]]


In [82]:
print(np.hstack((arr1,arr2)))

[[1 2 3 7 8 9]
 [4 5 6 0 0 0]]


- ##### 배열의 차원 변환

In [99]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr.base, arr.shape

###### 차원 추가

In [103]:
arr1 = np.expand_dims(arr, axis=0)

In [104]:
arr2 = np.expand_dims(arr, axis=1)

In [106]:
arr.shape, arr1.shape, arr2.shape

((12,), (1, 12), (12, 1))

In [120]:
arr.resize(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [126]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [148]:
arr.T 
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


##### 데이터 타입

In [149]:
arr = np.arange(20)

In [150]:
arr.dtype

dtype('int64')

In [151]:
arr = arr.astype(np.float32)
arr.dtype

dtype('float32')

In [159]:
arr = arr.reshape(4,-1)
arr

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]], dtype=float32)

In [166]:
arr = np.array([1,2,3],dtype = np.int32) # 4바이트 크기의 정수
arr.dtype, arr

(dtype('int32'), array([1, 2, 3], dtype=int32))

In [164]:
arr = np.array([1,2,3],dtype = np.float64) # 8바이트 크기의 실수수
arr.dtype, arr

(dtype('float64'), array([1., 2., 3.]))

In [165]:
arr = np.array([1,2,3],dtype=np.uint8) # 1바이트 크기의 부호 없는 정수(0~255)
arr.dtype, arr

(dtype('uint8'), array([1, 2, 3], dtype=uint8))

In [168]:
np.power(100, 8, dtype=np.int64) # correct

10000000000000000

In [169]:
np.power(100, 8, dtype=np.int32) # incorrect

1874919424

In [171]:
np.power(100, 100, dtype=np.float64) # correct

1e+200

In [172]:
np.power(100, 100, dtype=np.int64) # incorrect

0

In [173]:
np.iinfo(np.uint8)

iinfo(min=0, max=255, dtype=uint8)

In [178]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [179]:
np.iinfo(np.int32)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

##### 슬라이싱/인덱싱

##### 배열 조건 연산산

In [184]:
arr = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [185]:
arr[arr < 5]

array([1, 2, 3, 4])

In [188]:
cond = (arr >= 5)
arr[cond]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [187]:
arr[arr%2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [190]:
cond = (arr > 2) & (arr < 11)
arr[cond]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [191]:
cond = ( arr > 5) | (arr == 5)
arr[cond]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [193]:
np.any(arr>5)

True

In [194]:
np.all(arr > 5)

False

In [195]:
np.where(arr>5, 1, 0)

array([[0, 0, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 1, 1]])

### np.clip(array, min, max).   
- ##### 배열의 요소가 min보다 작으면 min으로 변경
- ##### 배열의 요소가 max보다 크면 max로 변경

In [196]:
np.clip(arr, 5, 8)

array([[5, 5, 5, 5],
       [5, 6, 7, 8],
       [8, 8, 8, 8]])

###### np.inf: 무한
###### np.nan: 결측치

In [198]:
arr = np.array([np.inf, np.nan, 3,4,5,np.nan,6,7])
arr

array([inf, nan,  3.,  4.,  5., nan,  6.,  7.])

In [200]:
is_inf = np.isinf(arr)
np.any(is_inf), np.all(is_inf)

is_nan = np.isnan(arr)
np.any(is_nan), np.all(is_nan)

(True, False)

In [202]:
is_inf = np.isnan(arr)
np.any(is_nan), np.all(is_nan)

(True, False)

In [203]:
np.isfinite(arr)

array([False, False,  True,  True,  True, False,  True,  True])

In [205]:
arr[np.isfinite(arr) == False] = 0
arr

array([0., 0., 3., 4., 5., 0., 6., 7.])

In [206]:
is_inf = np.isinf(arr)
np.any(is_inf), np.all(is_inf)

(False, False)

In [207]:
is_nan = np.isnan(arr)
np.any(is_nan), np.all(is_nan)

(False, False)

### 마스킹

In [208]:
lst=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

arr=np.array(lst)

In [217]:
mask=[True, False, False]
arr[:,mask]

array([[1],
       [4],
       [7]])

In [219]:
mask= arr>5
arr[mask]

array([6, 7, 8, 9])

### Broadcasting
> 배열의 모양이 다르더라도 어떠한 조건이 만족했을 때, 작은 배열을 자동으로 큰 배열 크기에 맞춘다.
> 
>행, 열 중 적어도 하나의 크기가 같아야 한다.